apiVersion: v1
kind: Service
metadata:
   name: db-python
   labels:
     name: postgres-service
     app: event-app
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30087
  selector:
    name: postgres-pod
    app: python-app